/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.oil;

import org.xtext.example.oil.OilStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class OilStandaloneSetup extends OilStandaloneSetupGenerated {
  public static void doSetup() {
    OilStandaloneSetup _oilStandaloneSetup = new OilStandaloneSetup();
    _oilStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
