/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.oil


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OilStandaloneSetup extends OilStandaloneSetupGenerated {

	def static void doSetup() {
		new OilStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
