/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.oil.oil;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Impl Attr Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.oil.oil.ImplAttrDef#isAuto <em>Auto</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.oil.oil.OilPackage#getImplAttrDef()
 * @model
 * @generated
 */
public interface ImplAttrDef extends ImplementationDef
{
  /**
   * Returns the value of the '<em><b>Auto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Auto</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Auto</em>' attribute.
   * @see #setAuto(boolean)
   * @see org.xtext.example.oil.oil.OilPackage#getImplAttrDef_Auto()
   * @model
   * @generated
   */
  boolean isAuto();

  /**
   * Sets the value of the '{@link org.xtext.example.oil.oil.ImplAttrDef#isAuto <em>Auto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Auto</em>' attribute.
   * @see #isAuto()
   * @generated
   */
  void setAuto(boolean value);

} // ImplAttrDef
