/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.oil.oil;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Object Ref Type Enum</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.oil.oil.OilPackage#getObjectRefTypeEnum()
 * @model
 * @generated
 */
public enum ObjectRefTypeEnum implements Enumerator
{
  /**
   * The '<em><b>OS TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OS_TYPE_VALUE
   * @generated
   * @ordered
   */
  OS_TYPE(0, "OS_TYPE", "OS_TYPE"),

  /**
   * The '<em><b>TASK TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TASK_TYPE_VALUE
   * @generated
   * @ordered
   */
  TASK_TYPE(1, "TASK_TYPE", "TASK_TYPE"),

  /**
   * The '<em><b>COUNTER TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COUNTER_TYPE_VALUE
   * @generated
   * @ordered
   */
  COUNTER_TYPE(2, "COUNTER_TYPE", "COUNTER_TYPE"),

  /**
   * The '<em><b>ALARM TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ALARM_TYPE_VALUE
   * @generated
   * @ordered
   */
  ALARM_TYPE(3, "ALARM_TYPE", "ALARM_TYPE"),

  /**
   * The '<em><b>RESOURCE TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RESOURCE_TYPE_VALUE
   * @generated
   * @ordered
   */
  RESOURCE_TYPE(4, "RESOURCE_TYPE", "RESOURCE_TYPE"),

  /**
   * The '<em><b>EVENT TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EVENT_TYPE_VALUE
   * @generated
   * @ordered
   */
  EVENT_TYPE(5, "EVENT_TYPE", "EVENT_TYPE"),

  /**
   * The '<em><b>ISR TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ISR_TYPE_VALUE
   * @generated
   * @ordered
   */
  ISR_TYPE(6, "ISR_TYPE", "ISR_TYPE"),

  /**
   * The '<em><b>MESSAGE TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MESSAGE_TYPE_VALUE
   * @generated
   * @ordered
   */
  MESSAGE_TYPE(7, "MESSAGE_TYPE", "MESSAGE_TYPE"),

  /**
   * The '<em><b>COM TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COM_TYPE_VALUE
   * @generated
   * @ordered
   */
  COM_TYPE(8, "COM_TYPE", "COM_TYPE"),

  /**
   * The '<em><b>NM TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NM_TYPE_VALUE
   * @generated
   * @ordered
   */
  NM_TYPE(9, "NM_TYPE", "NM_TYPE"),

  /**
   * The '<em><b>APPMODE TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #APPMODE_TYPE_VALUE
   * @generated
   * @ordered
   */
  APPMODE_TYPE(10, "APPMODE_TYPE", "APPMODE_TYPE"),

  /**
   * The '<em><b>IPDU TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IPDU_TYPE_VALUE
   * @generated
   * @ordered
   */
  IPDU_TYPE(11, "IPDU_TYPE", "IPDU_TYPE"),

  /**
   * The '<em><b>NETWORKMESSAGE TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NETWORKMESSAGE_TYPE_VALUE
   * @generated
   * @ordered
   */
  NETWORKMESSAGE_TYPE(12, "NETWORKMESSAGE_TYPE", "NETWORKMESSAGE_TYPE"),

  /**
   * The '<em><b>APPLICATION TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #APPLICATION_TYPE_VALUE
   * @generated
   * @ordered
   */
  APPLICATION_TYPE(13, "APPLICATION_TYPE", "APPLICATION_TYPE"),

  /**
   * The '<em><b>MEMOTY PROTECTION TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MEMOTY_PROTECTION_TYPE_VALUE
   * @generated
   * @ordered
   */
  MEMOTY_PROTECTION_TYPE(14, "MEMOTY_PROTECTION_TYPE", "MEMOTY_PROTECTION_TYPE"),

  /**
   * The '<em><b>SPINLOCK TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SPINLOCK_TYPE_VALUE
   * @generated
   * @ordered
   */
  SPINLOCK_TYPE(15, "SPINLOCK_TYPE", "SPINLOCK_TYPE"),

  /**
   * The '<em><b>SCHEDULETABLE TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SCHEDULETABLE_TYPE_VALUE
   * @generated
   * @ordered
   */
  SCHEDULETABLE_TYPE(16, "SCHEDULETABLE_TYPE", "SCHEDULETABLE_TYPE"),

  /**
   * The '<em><b>IOC TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IOC_TYPE_VALUE
   * @generated
   * @ordered
   */
  IOC_TYPE(17, "IOC_TYPE", "IOC_TYPE"),

  /**
   * The '<em><b>APICONFIG TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #APICONFIG_TYPE_VALUE
   * @generated
   * @ordered
   */
  APICONFIG_TYPE(18, "APICONFIG_TYPE", "APICONFIG_TYPE"),

  /**
   * The '<em><b>LIBRARY TYPE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIBRARY_TYPE_VALUE
   * @generated
   * @ordered
   */
  LIBRARY_TYPE(19, "LIBRARY_TYPE", "LIBRARY_TYPE");

  /**
   * The '<em><b>OS TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>OS TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #OS_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int OS_TYPE_VALUE = 0;

  /**
   * The '<em><b>TASK TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>TASK TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TASK_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int TASK_TYPE_VALUE = 1;

  /**
   * The '<em><b>COUNTER TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>COUNTER TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #COUNTER_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int COUNTER_TYPE_VALUE = 2;

  /**
   * The '<em><b>ALARM TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ALARM TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ALARM_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int ALARM_TYPE_VALUE = 3;

  /**
   * The '<em><b>RESOURCE TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>RESOURCE TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #RESOURCE_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int RESOURCE_TYPE_VALUE = 4;

  /**
   * The '<em><b>EVENT TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>EVENT TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EVENT_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int EVENT_TYPE_VALUE = 5;

  /**
   * The '<em><b>ISR TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>ISR TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ISR_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int ISR_TYPE_VALUE = 6;

  /**
   * The '<em><b>MESSAGE TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>MESSAGE TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MESSAGE_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int MESSAGE_TYPE_VALUE = 7;

  /**
   * The '<em><b>COM TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>COM TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #COM_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int COM_TYPE_VALUE = 8;

  /**
   * The '<em><b>NM TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NM TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NM_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int NM_TYPE_VALUE = 9;

  /**
   * The '<em><b>APPMODE TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>APPMODE TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #APPMODE_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int APPMODE_TYPE_VALUE = 10;

  /**
   * The '<em><b>IPDU TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>IPDU TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #IPDU_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int IPDU_TYPE_VALUE = 11;

  /**
   * The '<em><b>NETWORKMESSAGE TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>NETWORKMESSAGE TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NETWORKMESSAGE_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int NETWORKMESSAGE_TYPE_VALUE = 12;

  /**
   * The '<em><b>APPLICATION TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>APPLICATION TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #APPLICATION_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int APPLICATION_TYPE_VALUE = 13;

  /**
   * The '<em><b>MEMOTY PROTECTION TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>MEMOTY PROTECTION TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MEMOTY_PROTECTION_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int MEMOTY_PROTECTION_TYPE_VALUE = 14;

  /**
   * The '<em><b>SPINLOCK TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SPINLOCK TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SPINLOCK_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int SPINLOCK_TYPE_VALUE = 15;

  /**
   * The '<em><b>SCHEDULETABLE TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>SCHEDULETABLE TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SCHEDULETABLE_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int SCHEDULETABLE_TYPE_VALUE = 16;

  /**
   * The '<em><b>IOC TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>IOC TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #IOC_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int IOC_TYPE_VALUE = 17;

  /**
   * The '<em><b>APICONFIG TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>APICONFIG TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #APICONFIG_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int APICONFIG_TYPE_VALUE = 18;

  /**
   * The '<em><b>LIBRARY TYPE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>LIBRARY TYPE</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LIBRARY_TYPE
   * @model
   * @generated
   * @ordered
   */
  public static final int LIBRARY_TYPE_VALUE = 19;

  /**
   * An array of all the '<em><b>Object Ref Type Enum</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ObjectRefTypeEnum[] VALUES_ARRAY =
    new ObjectRefTypeEnum[]
    {
      OS_TYPE,
      TASK_TYPE,
      COUNTER_TYPE,
      ALARM_TYPE,
      RESOURCE_TYPE,
      EVENT_TYPE,
      ISR_TYPE,
      MESSAGE_TYPE,
      COM_TYPE,
      NM_TYPE,
      APPMODE_TYPE,
      IPDU_TYPE,
      NETWORKMESSAGE_TYPE,
      APPLICATION_TYPE,
      MEMOTY_PROTECTION_TYPE,
      SPINLOCK_TYPE,
      SCHEDULETABLE_TYPE,
      IOC_TYPE,
      APICONFIG_TYPE,
      LIBRARY_TYPE,
    };

  /**
   * A public read-only list of all the '<em><b>Object Ref Type Enum</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ObjectRefTypeEnum> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Object Ref Type Enum</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ObjectRefTypeEnum get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ObjectRefTypeEnum result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Object Ref Type Enum</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ObjectRefTypeEnum getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ObjectRefTypeEnum result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Object Ref Type Enum</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ObjectRefTypeEnum get(int value)
  {
    switch (value)
    {
      case OS_TYPE_VALUE: return OS_TYPE;
      case TASK_TYPE_VALUE: return TASK_TYPE;
      case COUNTER_TYPE_VALUE: return COUNTER_TYPE;
      case ALARM_TYPE_VALUE: return ALARM_TYPE;
      case RESOURCE_TYPE_VALUE: return RESOURCE_TYPE;
      case EVENT_TYPE_VALUE: return EVENT_TYPE;
      case ISR_TYPE_VALUE: return ISR_TYPE;
      case MESSAGE_TYPE_VALUE: return MESSAGE_TYPE;
      case COM_TYPE_VALUE: return COM_TYPE;
      case NM_TYPE_VALUE: return NM_TYPE;
      case APPMODE_TYPE_VALUE: return APPMODE_TYPE;
      case IPDU_TYPE_VALUE: return IPDU_TYPE;
      case NETWORKMESSAGE_TYPE_VALUE: return NETWORKMESSAGE_TYPE;
      case APPLICATION_TYPE_VALUE: return APPLICATION_TYPE;
      case MEMOTY_PROTECTION_TYPE_VALUE: return MEMOTY_PROTECTION_TYPE;
      case SPINLOCK_TYPE_VALUE: return SPINLOCK_TYPE;
      case SCHEDULETABLE_TYPE_VALUE: return SCHEDULETABLE_TYPE;
      case IOC_TYPE_VALUE: return IOC_TYPE;
      case APICONFIG_TYPE_VALUE: return APICONFIG_TYPE;
      case LIBRARY_TYPE_VALUE: return LIBRARY_TYPE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ObjectRefTypeEnum(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ObjectRefTypeEnum
