/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.oil.oil.util;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

import org.xtext.example.oil.oil.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.oil.oil.OilPackage
 * @generated
 */
public class OilAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static OilPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public OilAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = OilPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OilSwitch<Adapter> modelSwitch =
    new OilSwitch<Adapter>()
    {
      @Override
      public Adapter caseOILFile(OILFile object)
      {
        return createOILFileAdapter();
      }
      @Override
      public Adapter caseInclude(Include object)
      {
        return createIncludeAdapter();
      }
      @Override
      public Adapter caseOILVersion(OILVersion object)
      {
        return createOILVersionAdapter();
      }
      @Override
      public Adapter caseImplementationDefinition(ImplementationDefinition object)
      {
        return createImplementationDefinitionAdapter();
      }
      @Override
      public Adapter caseImplementationSpec(ImplementationSpec object)
      {
        return createImplementationSpecAdapter();
      }
      @Override
      public Adapter caseImpTaskRule(ImpTaskRule object)
      {
        return createImpTaskRuleAdapter();
      }
      @Override
      public Adapter caseImpTaskParam(ImpTaskParam object)
      {
        return createImpTaskParamAdapter();
      }
      @Override
      public Adapter caseImpOsRule(ImpOsRule object)
      {
        return createImpOsRuleAdapter();
      }
      @Override
      public Adapter caseImpOsParam(ImpOsParam object)
      {
        return createImpOsParamAdapter();
      }
      @Override
      public Adapter caseImpCounterRule(ImpCounterRule object)
      {
        return createImpCounterRuleAdapter();
      }
      @Override
      public Adapter caseImpCounterParam(ImpCounterParam object)
      {
        return createImpCounterParamAdapter();
      }
      @Override
      public Adapter caseApplicationRule(ApplicationRule object)
      {
        return createApplicationRuleAdapter();
      }
      @Override
      public Adapter caseAppSubContainer(AppSubContainer object)
      {
        return createAppSubContainerAdapter();
      }
      @Override
      public Adapter caseApplicationParam(ApplicationParam object)
      {
        return createApplicationParamAdapter();
      }
      @Override
      public Adapter caseHasRestartTaskRule(HasRestartTaskRule object)
      {
        return createHasRestartTaskRuleAdapter();
      }
      @Override
      public Adapter caseRestartTaskRule(RestartTaskRule object)
      {
        return createRestartTaskRuleAdapter();
      }
      @Override
      public Adapter caseTrustedRule(TrustedRule object)
      {
        return createTrustedRuleAdapter();
      }
      @Override
      public Adapter caseTrustedFucRule(TrustedFucRule object)
      {
        return createTrustedFucRuleAdapter();
      }
      @Override
      public Adapter caseIsrRule(IsrRule object)
      {
        return createIsrRuleAdapter();
      }
      @Override
      public Adapter caseIsrSubContainer(IsrSubContainer object)
      {
        return createIsrSubContainerAdapter();
      }
      @Override
      public Adapter caseTimingProtectionRule(TimingProtectionRule object)
      {
        return createTimingProtectionRuleAdapter();
      }
      @Override
      public Adapter caseTimingProtectionParam(TimingProtectionParam object)
      {
        return createTimingProtectionParamAdapter();
      }
      @Override
      public Adapter caseIsrParam(IsrParam object)
      {
        return createIsrParamAdapter();
      }
      @Override
      public Adapter caseMemoryProtectionRule(MemoryProtectionRule object)
      {
        return createMemoryProtectionRuleAdapter();
      }
      @Override
      public Adapter caseImplementationDef(ImplementationDef object)
      {
        return createImplementationDefAdapter();
      }
      @Override
      public Adapter caseImplAttrDef(ImplAttrDef object)
      {
        return createImplAttrDefAdapter();
      }
      @Override
      public Adapter caseImplAttrIntDef(ImplAttrIntDef object)
      {
        return createImplAttrIntDefAdapter();
      }
      @Override
      public Adapter caseImplAttrFloatDef(ImplAttrFloatDef object)
      {
        return createImplAttrFloatDefAdapter();
      }
      @Override
      public Adapter caseImplAttrEnumDef(ImplAttrEnumDef object)
      {
        return createImplAttrEnumDefAdapter();
      }
      @Override
      public Adapter caseImplAttrStringDef(ImplAttrStringDef object)
      {
        return createImplAttrStringDefAdapter();
      }
      @Override
      public Adapter caseImplAttrBooleanDef(ImplAttrBooleanDef object)
      {
        return createImplAttrBooleanDefAdapter();
      }
      @Override
      public Adapter caseImplAttrIdentiFier(ImplAttrIdentiFier object)
      {
        return createImplAttrIdentiFierAdapter();
      }
      @Override
      public Adapter caseRange(Range object)
      {
        return createRangeAdapter();
      }
      @Override
      public Adapter caseEnumeration(Enumeration object)
      {
        return createEnumerationAdapter();
      }
      @Override
      public Adapter caseEnumerator(Enumerator object)
      {
        return createEnumeratorAdapter();
      }
      @Override
      public Adapter caseImplRefDef(ImplRefDef object)
      {
        return createImplRefDefAdapter();
      }
      @Override
      public Adapter caseApplicationDefinition(ApplicationDefinition object)
      {
        return createApplicationDefinitionAdapter();
      }
      @Override
      public Adapter caseObjectDefinition(ObjectDefinition object)
      {
        return createObjectDefinitionAdapter();
      }
      @Override
      public Adapter caseEventRule(EventRule object)
      {
        return createEventRuleAdapter();
      }
      @Override
      public Adapter caseAppmodeRule(AppmodeRule object)
      {
        return createAppmodeRuleAdapter();
      }
      @Override
      public Adapter caseMessageRule(MessageRule object)
      {
        return createMessageRuleAdapter();
      }
      @Override
      public Adapter caseMessageattribute(Messageattribute object)
      {
        return createMessageattributeAdapter();
      }
      @Override
      public Adapter caseMessageattribute3(Messageattribute3 object)
      {
        return createMessageattribute3Adapter();
      }
      @Override
      public Adapter caseMessageSETEVENT(MessageSETEVENT object)
      {
        return createMessageSETEVENTAdapter();
      }
      @Override
      public Adapter caseMessageCOMCALLBACK(MessageCOMCALLBACK object)
      {
        return createMessageCOMCALLBACKAdapter();
      }
      @Override
      public Adapter caseMessageattribute2(Messageattribute2 object)
      {
        return createMessageattribute2Adapter();
      }
      @Override
      public Adapter caseMessage_SEND_STATIC_EXTERNAL(Message_SEND_STATIC_EXTERNAL object)
      {
        return createMessage_SEND_STATIC_EXTERNALAdapter();
      }
      @Override
      public Adapter caseMessage_SEND_DYNAMIC_EXTERNAL(Message_SEND_DYNAMIC_EXTERNAL object)
      {
        return createMessage_SEND_DYNAMIC_EXTERNALAdapter();
      }
      @Override
      public Adapter caseMessage_SEND_ZERO_EXTERNAL(Message_SEND_ZERO_EXTERNAL object)
      {
        return createMessage_SEND_ZERO_EXTERNALAdapter();
      }
      @Override
      public Adapter caseMessage_RECEIVE_ZERO_INTERNAL(Message_RECEIVE_ZERO_INTERNAL object)
      {
        return createMessage_RECEIVE_ZERO_INTERNALAdapter();
      }
      @Override
      public Adapter caseMessage_RECEIVE_ZERO_EXTERNAL(Message_RECEIVE_ZERO_EXTERNAL object)
      {
        return createMessage_RECEIVE_ZERO_EXTERNALAdapter();
      }
      @Override
      public Adapter caseMessage_RECEIVE_UNQUEUED_INTERNAL(Message_RECEIVE_UNQUEUED_INTERNAL object)
      {
        return createMessage_RECEIVE_UNQUEUED_INTERNALAdapter();
      }
      @Override
      public Adapter caseMessage_RECEIVE_QUEUED_INTERNAL(Message_RECEIVE_QUEUED_INTERNAL object)
      {
        return createMessage_RECEIVE_QUEUED_INTERNALAdapter();
      }
      @Override
      public Adapter caseMessage_RECEIVE_UNQUEUED_EXTERNAL(Message_RECEIVE_UNQUEUED_EXTERNAL object)
      {
        return createMessage_RECEIVE_UNQUEUED_EXTERNALAdapter();
      }
      @Override
      public Adapter caseMessage_RECEIVE_QUEUED_EXTERNAL(Message_RECEIVE_QUEUED_EXTERNAL object)
      {
        return createMessage_RECEIVE_QUEUED_EXTERNALAdapter();
      }
      @Override
      public Adapter caseMessage_RECEIVE_DYNAMIC_EXTERNAL(Message_RECEIVE_DYNAMIC_EXTERNAL object)
      {
        return createMessage_RECEIVE_DYNAMIC_EXTERNALAdapter();
      }
      @Override
      public Adapter caseMessage_RECEIVE_ZERO_SENDERS(Message_RECEIVE_ZERO_SENDERS object)
      {
        return createMessage_RECEIVE_ZERO_SENDERSAdapter();
      }
      @Override
      public Adapter caseMessageCDATATYPE(MessageCDATATYPE object)
      {
        return createMessageCDATATYPEAdapter();
      }
      @Override
      public Adapter caseMessageTRANSFERPROPERTY(MessageTRANSFERPROPERTY object)
      {
        return createMessageTRANSFERPROPERTYAdapter();
      }
      @Override
      public Adapter caseMessageNETWORKORDERCALLOUT(MessageNETWORKORDERCALLOUT object)
      {
        return createMessageNETWORKORDERCALLOUTAdapter();
      }
      @Override
      public Adapter caseMessageCPUORDERCALLOUT(MessageCPUORDERCALLOUT object)
      {
        return createMessageCPUORDERCALLOUTAdapter();
      }
      @Override
      public Adapter caseMessageINITIALVALUE(MessageINITIALVALUE object)
      {
        return createMessageINITIALVALUEAdapter();
      }
      @Override
      public Adapter caseMessageNETWORKMESSAGE(MessageNETWORKMESSAGE object)
      {
        return createMessageNETWORKMESSAGEAdapter();
      }
      @Override
      public Adapter caseMessageSENDINGMESSAGE(MessageSENDINGMESSAGE object)
      {
        return createMessageSENDINGMESSAGEAdapter();
      }
      @Override
      public Adapter caseMessageQUEUESIZE(MessageQUEUESIZE object)
      {
        return createMessageQUEUESIZEAdapter();
      }
      @Override
      public Adapter caseMessagefilter(Messagefilter object)
      {
        return createMessagefilterAdapter();
      }
      @Override
      public Adapter caseMessageLINK(MessageLINK object)
      {
        return createMessageLINKAdapter();
      }
      @Override
      public Adapter caseLibrayattribute(Librayattribute object)
      {
        return createLibrayattributeAdapter();
      }
      @Override
      public Adapter caseComRule(ComRule object)
      {
        return createComRuleAdapter();
      }
      @Override
      public Adapter caseComattribute(Comattribute object)
      {
        return createComattributeAdapter();
      }
      @Override
      public Adapter caseTaskRule(TaskRule object)
      {
        return createTaskRuleAdapter();
      }
      @Override
      public Adapter caseTaskattribute(Taskattribute object)
      {
        return createTaskattributeAdapter();
      }
      @Override
      public Adapter caseTaskTimingAttribute(TaskTimingAttribute object)
      {
        return createTaskTimingAttributeAdapter();
      }
      @Override
      public Adapter caseTaskAutostartAttribute(TaskAutostartAttribute object)
      {
        return createTaskAutostartAttributeAdapter();
      }
      @Override
      public Adapter caseResourceRule(ResourceRule object)
      {
        return createResourceRuleAdapter();
      }
      @Override
      public Adapter caseResourceattribute(Resourceattribute object)
      {
        return createResourceattributeAdapter();
      }
      @Override
      public Adapter caseAlarmRule(AlarmRule object)
      {
        return createAlarmRuleAdapter();
      }
      @Override
      public Adapter caseAlarmAttribute(AlarmAttribute object)
      {
        return createAlarmAttributeAdapter();
      }
      @Override
      public Adapter caseAlarmActionAttribute(AlarmActionAttribute object)
      {
        return createAlarmActionAttributeAdapter();
      }
      @Override
      public Adapter caseAlarmAutostartAttribute(AlarmAutostartAttribute object)
      {
        return createAlarmAutostartAttributeAdapter();
      }
      @Override
      public Adapter caseScheduleTableRule(ScheduleTableRule object)
      {
        return createScheduleTableRuleAdapter();
      }
      @Override
      public Adapter caseScheduleTableAttribute(ScheduleTableAttribute object)
      {
        return createScheduleTableAttributeAdapter();
      }
      @Override
      public Adapter caseScheduleAutoStartAttribute(ScheduleAutoStartAttribute object)
      {
        return createScheduleAutoStartAttributeAdapter();
      }
      @Override
      public Adapter caseSchduleSynAttribute(SchduleSynAttribute object)
      {
        return createSchduleSynAttributeAdapter();
      }
      @Override
      public Adapter caseExpiryAttribute(ExpiryAttribute object)
      {
        return createExpiryAttributeAdapter();
      }
      @Override
      public Adapter caseSchduleActionAttribute(SchduleActionAttribute object)
      {
        return createSchduleActionAttributeAdapter();
      }
      @Override
      public Adapter caseIocRule(IocRule object)
      {
        return createIocRuleAdapter();
      }
      @Override
      public Adapter caseIocAttribute(IocAttribute object)
      {
        return createIocAttributeAdapter();
      }
      @Override
      public Adapter caseIocSender(IocSender object)
      {
        return createIocSenderAdapter();
      }
      @Override
      public Adapter caseIocReceiver(IocReceiver object)
      {
        return createIocReceiverAdapter();
      }
      @Override
      public Adapter caseIocDataTypeAttr(IocDataTypeAttr object)
      {
        return createIocDataTypeAttrAdapter();
      }
      @Override
      public Adapter caseIocSemantics(IocSemantics object)
      {
        return createIocSemanticsAdapter();
      }
      @Override
      public Adapter caseAttribute(Attribute object)
      {
        return createAttributeAdapter();
      }
      @Override
      public Adapter caseAttributeName(AttributeName object)
      {
        return createAttributeNameAdapter();
      }
      @Override
      public Adapter caseAttributeValue(AttributeValue object)
      {
        return createAttributeValueAdapter();
      }
      @Override
      public Adapter caseNameAttributeValue(NameAttributeValue object)
      {
        return createNameAttributeValueAdapter();
      }
      @Override
      public Adapter caseBooleanAttributeValue(BooleanAttributeValue object)
      {
        return createBooleanAttributeValueAdapter();
      }
      @Override
      public Adapter caseNumberAttributeValue(NumberAttributeValue object)
      {
        return createNumberAttributeValueAdapter();
      }
      @Override
      public Adapter caseFloatAttributeValue(FloatAttributeValue object)
      {
        return createFloatAttributeValueAdapter();
      }
      @Override
      public Adapter caseStringAttributeValue(StringAttributeValue object)
      {
        return createStringAttributeValueAdapter();
      }
      @Override
      public Adapter caseAutoAttributeValue(AutoAttributeValue object)
      {
        return createAutoAttributeValueAdapter();
      }
      @Override
      public Adapter caseOsRule(OsRule object)
      {
        return createOsRuleAdapter();
      }
      @Override
      public Adapter caseCounterRule(CounterRule object)
      {
        return createCounterRuleAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.OILFile <em>OIL File</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.OILFile
   * @generated
   */
  public Adapter createOILFileAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Include <em>Include</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Include
   * @generated
   */
  public Adapter createIncludeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.OILVersion <em>OIL Version</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.OILVersion
   * @generated
   */
  public Adapter createOILVersionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplementationDefinition <em>Implementation Definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplementationDefinition
   * @generated
   */
  public Adapter createImplementationDefinitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplementationSpec <em>Implementation Spec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplementationSpec
   * @generated
   */
  public Adapter createImplementationSpecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImpTaskRule <em>Imp Task Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImpTaskRule
   * @generated
   */
  public Adapter createImpTaskRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImpTaskParam <em>Imp Task Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImpTaskParam
   * @generated
   */
  public Adapter createImpTaskParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImpOsRule <em>Imp Os Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImpOsRule
   * @generated
   */
  public Adapter createImpOsRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImpOsParam <em>Imp Os Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImpOsParam
   * @generated
   */
  public Adapter createImpOsParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImpCounterRule <em>Imp Counter Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImpCounterRule
   * @generated
   */
  public Adapter createImpCounterRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImpCounterParam <em>Imp Counter Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImpCounterParam
   * @generated
   */
  public Adapter createImpCounterParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ApplicationRule <em>Application Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ApplicationRule
   * @generated
   */
  public Adapter createApplicationRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.AppSubContainer <em>App Sub Container</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.AppSubContainer
   * @generated
   */
  public Adapter createAppSubContainerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ApplicationParam <em>Application Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ApplicationParam
   * @generated
   */
  public Adapter createApplicationParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.HasRestartTaskRule <em>Has Restart Task Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.HasRestartTaskRule
   * @generated
   */
  public Adapter createHasRestartTaskRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.RestartTaskRule <em>Restart Task Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.RestartTaskRule
   * @generated
   */
  public Adapter createRestartTaskRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.TrustedRule <em>Trusted Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.TrustedRule
   * @generated
   */
  public Adapter createTrustedRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.TrustedFucRule <em>Trusted Fuc Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.TrustedFucRule
   * @generated
   */
  public Adapter createTrustedFucRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.IsrRule <em>Isr Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.IsrRule
   * @generated
   */
  public Adapter createIsrRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.IsrSubContainer <em>Isr Sub Container</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.IsrSubContainer
   * @generated
   */
  public Adapter createIsrSubContainerAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.TimingProtectionRule <em>Timing Protection Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.TimingProtectionRule
   * @generated
   */
  public Adapter createTimingProtectionRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.TimingProtectionParam <em>Timing Protection Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.TimingProtectionParam
   * @generated
   */
  public Adapter createTimingProtectionParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.IsrParam <em>Isr Param</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.IsrParam
   * @generated
   */
  public Adapter createIsrParamAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MemoryProtectionRule <em>Memory Protection Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MemoryProtectionRule
   * @generated
   */
  public Adapter createMemoryProtectionRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplementationDef <em>Implementation Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplementationDef
   * @generated
   */
  public Adapter createImplementationDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplAttrDef <em>Impl Attr Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplAttrDef
   * @generated
   */
  public Adapter createImplAttrDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplAttrIntDef <em>Impl Attr Int Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplAttrIntDef
   * @generated
   */
  public Adapter createImplAttrIntDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplAttrFloatDef <em>Impl Attr Float Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplAttrFloatDef
   * @generated
   */
  public Adapter createImplAttrFloatDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplAttrEnumDef <em>Impl Attr Enum Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplAttrEnumDef
   * @generated
   */
  public Adapter createImplAttrEnumDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplAttrStringDef <em>Impl Attr String Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplAttrStringDef
   * @generated
   */
  public Adapter createImplAttrStringDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplAttrBooleanDef <em>Impl Attr Boolean Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplAttrBooleanDef
   * @generated
   */
  public Adapter createImplAttrBooleanDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplAttrIdentiFier <em>Impl Attr Identi Fier</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplAttrIdentiFier
   * @generated
   */
  public Adapter createImplAttrIdentiFierAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Range <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Range
   * @generated
   */
  public Adapter createRangeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Enumeration <em>Enumeration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Enumeration
   * @generated
   */
  public Adapter createEnumerationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Enumerator <em>Enumerator</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Enumerator
   * @generated
   */
  public Adapter createEnumeratorAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ImplRefDef <em>Impl Ref Def</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ImplRefDef
   * @generated
   */
  public Adapter createImplRefDefAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ApplicationDefinition <em>Application Definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ApplicationDefinition
   * @generated
   */
  public Adapter createApplicationDefinitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ObjectDefinition <em>Object Definition</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ObjectDefinition
   * @generated
   */
  public Adapter createObjectDefinitionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.EventRule <em>Event Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.EventRule
   * @generated
   */
  public Adapter createEventRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.AppmodeRule <em>Appmode Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.AppmodeRule
   * @generated
   */
  public Adapter createAppmodeRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageRule <em>Message Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageRule
   * @generated
   */
  public Adapter createMessageRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Messageattribute <em>Messageattribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Messageattribute
   * @generated
   */
  public Adapter createMessageattributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Messageattribute3 <em>Messageattribute3</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Messageattribute3
   * @generated
   */
  public Adapter createMessageattribute3Adapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageSETEVENT <em>Message SETEVENT</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageSETEVENT
   * @generated
   */
  public Adapter createMessageSETEVENTAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageCOMCALLBACK <em>Message COMCALLBACK</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageCOMCALLBACK
   * @generated
   */
  public Adapter createMessageCOMCALLBACKAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Messageattribute2 <em>Messageattribute2</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Messageattribute2
   * @generated
   */
  public Adapter createMessageattribute2Adapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_SEND_STATIC_EXTERNAL <em>Message SEND STATIC EXTERNAL</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_SEND_STATIC_EXTERNAL
   * @generated
   */
  public Adapter createMessage_SEND_STATIC_EXTERNALAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_SEND_DYNAMIC_EXTERNAL <em>Message SEND DYNAMIC EXTERNAL</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_SEND_DYNAMIC_EXTERNAL
   * @generated
   */
  public Adapter createMessage_SEND_DYNAMIC_EXTERNALAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_SEND_ZERO_EXTERNAL <em>Message SEND ZERO EXTERNAL</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_SEND_ZERO_EXTERNAL
   * @generated
   */
  public Adapter createMessage_SEND_ZERO_EXTERNALAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_RECEIVE_ZERO_INTERNAL <em>Message RECEIVE ZERO INTERNAL</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_RECEIVE_ZERO_INTERNAL
   * @generated
   */
  public Adapter createMessage_RECEIVE_ZERO_INTERNALAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_RECEIVE_ZERO_EXTERNAL <em>Message RECEIVE ZERO EXTERNAL</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_RECEIVE_ZERO_EXTERNAL
   * @generated
   */
  public Adapter createMessage_RECEIVE_ZERO_EXTERNALAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_RECEIVE_UNQUEUED_INTERNAL <em>Message RECEIVE UNQUEUED INTERNAL</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_RECEIVE_UNQUEUED_INTERNAL
   * @generated
   */
  public Adapter createMessage_RECEIVE_UNQUEUED_INTERNALAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_RECEIVE_QUEUED_INTERNAL <em>Message RECEIVE QUEUED INTERNAL</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_RECEIVE_QUEUED_INTERNAL
   * @generated
   */
  public Adapter createMessage_RECEIVE_QUEUED_INTERNALAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_RECEIVE_UNQUEUED_EXTERNAL <em>Message RECEIVE UNQUEUED EXTERNAL</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_RECEIVE_UNQUEUED_EXTERNAL
   * @generated
   */
  public Adapter createMessage_RECEIVE_UNQUEUED_EXTERNALAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_RECEIVE_QUEUED_EXTERNAL <em>Message RECEIVE QUEUED EXTERNAL</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_RECEIVE_QUEUED_EXTERNAL
   * @generated
   */
  public Adapter createMessage_RECEIVE_QUEUED_EXTERNALAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_RECEIVE_DYNAMIC_EXTERNAL <em>Message RECEIVE DYNAMIC EXTERNAL</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_RECEIVE_DYNAMIC_EXTERNAL
   * @generated
   */
  public Adapter createMessage_RECEIVE_DYNAMIC_EXTERNALAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Message_RECEIVE_ZERO_SENDERS <em>Message RECEIVE ZERO SENDERS</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Message_RECEIVE_ZERO_SENDERS
   * @generated
   */
  public Adapter createMessage_RECEIVE_ZERO_SENDERSAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageCDATATYPE <em>Message CDATATYPE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageCDATATYPE
   * @generated
   */
  public Adapter createMessageCDATATYPEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageTRANSFERPROPERTY <em>Message TRANSFERPROPERTY</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageTRANSFERPROPERTY
   * @generated
   */
  public Adapter createMessageTRANSFERPROPERTYAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageNETWORKORDERCALLOUT <em>Message NETWORKORDERCALLOUT</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageNETWORKORDERCALLOUT
   * @generated
   */
  public Adapter createMessageNETWORKORDERCALLOUTAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageCPUORDERCALLOUT <em>Message CPUORDERCALLOUT</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageCPUORDERCALLOUT
   * @generated
   */
  public Adapter createMessageCPUORDERCALLOUTAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageINITIALVALUE <em>Message INITIALVALUE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageINITIALVALUE
   * @generated
   */
  public Adapter createMessageINITIALVALUEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageNETWORKMESSAGE <em>Message NETWORKMESSAGE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageNETWORKMESSAGE
   * @generated
   */
  public Adapter createMessageNETWORKMESSAGEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageSENDINGMESSAGE <em>Message SENDINGMESSAGE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageSENDINGMESSAGE
   * @generated
   */
  public Adapter createMessageSENDINGMESSAGEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageQUEUESIZE <em>Message QUEUESIZE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageQUEUESIZE
   * @generated
   */
  public Adapter createMessageQUEUESIZEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Messagefilter <em>Messagefilter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Messagefilter
   * @generated
   */
  public Adapter createMessagefilterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.MessageLINK <em>Message LINK</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.MessageLINK
   * @generated
   */
  public Adapter createMessageLINKAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Librayattribute <em>Librayattribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Librayattribute
   * @generated
   */
  public Adapter createLibrayattributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ComRule <em>Com Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ComRule
   * @generated
   */
  public Adapter createComRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Comattribute <em>Comattribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Comattribute
   * @generated
   */
  public Adapter createComattributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.TaskRule <em>Task Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.TaskRule
   * @generated
   */
  public Adapter createTaskRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Taskattribute <em>Taskattribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Taskattribute
   * @generated
   */
  public Adapter createTaskattributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.TaskTimingAttribute <em>Task Timing Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.TaskTimingAttribute
   * @generated
   */
  public Adapter createTaskTimingAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.TaskAutostartAttribute <em>Task Autostart Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.TaskAutostartAttribute
   * @generated
   */
  public Adapter createTaskAutostartAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ResourceRule <em>Resource Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ResourceRule
   * @generated
   */
  public Adapter createResourceRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Resourceattribute <em>Resourceattribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Resourceattribute
   * @generated
   */
  public Adapter createResourceattributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.AlarmRule <em>Alarm Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.AlarmRule
   * @generated
   */
  public Adapter createAlarmRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.AlarmAttribute <em>Alarm Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.AlarmAttribute
   * @generated
   */
  public Adapter createAlarmAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.AlarmActionAttribute <em>Alarm Action Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.AlarmActionAttribute
   * @generated
   */
  public Adapter createAlarmActionAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.AlarmAutostartAttribute <em>Alarm Autostart Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.AlarmAutostartAttribute
   * @generated
   */
  public Adapter createAlarmAutostartAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ScheduleTableRule <em>Schedule Table Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ScheduleTableRule
   * @generated
   */
  public Adapter createScheduleTableRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ScheduleTableAttribute <em>Schedule Table Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ScheduleTableAttribute
   * @generated
   */
  public Adapter createScheduleTableAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ScheduleAutoStartAttribute <em>Schedule Auto Start Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ScheduleAutoStartAttribute
   * @generated
   */
  public Adapter createScheduleAutoStartAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.SchduleSynAttribute <em>Schdule Syn Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.SchduleSynAttribute
   * @generated
   */
  public Adapter createSchduleSynAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.ExpiryAttribute <em>Expiry Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.ExpiryAttribute
   * @generated
   */
  public Adapter createExpiryAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.SchduleActionAttribute <em>Schdule Action Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.SchduleActionAttribute
   * @generated
   */
  public Adapter createSchduleActionAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.IocRule <em>Ioc Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.IocRule
   * @generated
   */
  public Adapter createIocRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.IocAttribute <em>Ioc Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.IocAttribute
   * @generated
   */
  public Adapter createIocAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.IocSender <em>Ioc Sender</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.IocSender
   * @generated
   */
  public Adapter createIocSenderAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.IocReceiver <em>Ioc Receiver</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.IocReceiver
   * @generated
   */
  public Adapter createIocReceiverAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.IocDataTypeAttr <em>Ioc Data Type Attr</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.IocDataTypeAttr
   * @generated
   */
  public Adapter createIocDataTypeAttrAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.IocSemantics <em>Ioc Semantics</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.IocSemantics
   * @generated
   */
  public Adapter createIocSemanticsAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.Attribute
   * @generated
   */
  public Adapter createAttributeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.AttributeName <em>Attribute Name</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.AttributeName
   * @generated
   */
  public Adapter createAttributeNameAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.AttributeValue <em>Attribute Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.AttributeValue
   * @generated
   */
  public Adapter createAttributeValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.NameAttributeValue <em>Name Attribute Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.NameAttributeValue
   * @generated
   */
  public Adapter createNameAttributeValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.BooleanAttributeValue <em>Boolean Attribute Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.BooleanAttributeValue
   * @generated
   */
  public Adapter createBooleanAttributeValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.NumberAttributeValue <em>Number Attribute Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.NumberAttributeValue
   * @generated
   */
  public Adapter createNumberAttributeValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.FloatAttributeValue <em>Float Attribute Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.FloatAttributeValue
   * @generated
   */
  public Adapter createFloatAttributeValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.StringAttributeValue <em>String Attribute Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.StringAttributeValue
   * @generated
   */
  public Adapter createStringAttributeValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.AutoAttributeValue <em>Auto Attribute Value</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.AutoAttributeValue
   * @generated
   */
  public Adapter createAutoAttributeValueAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.OsRule <em>Os Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.OsRule
   * @generated
   */
  public Adapter createOsRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link org.xtext.example.oil.oil.CounterRule <em>Counter Rule</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see org.xtext.example.oil.oil.CounterRule
   * @generated
   */
  public Adapter createCounterRuleAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //OilAdapterFactory
