/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.oil.oil.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.oil.oil.DefaultEnum;
import org.xtext.example.oil.oil.ImplAttrBooleanDef;
import org.xtext.example.oil.oil.ImplementationDef;
import org.xtext.example.oil.oil.OilPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Impl Attr Boolean Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.oil.oil.impl.ImplAttrBooleanDefImpl#getTrueParameterList <em>True Parameter List</em>}</li>
 *   <li>{@link org.xtext.example.oil.oil.impl.ImplAttrBooleanDefImpl#getTrueDescription <em>True Description</em>}</li>
 *   <li>{@link org.xtext.example.oil.oil.impl.ImplAttrBooleanDefImpl#getFalseParameterList <em>False Parameter List</em>}</li>
 *   <li>{@link org.xtext.example.oil.oil.impl.ImplAttrBooleanDefImpl#getFalseDescription <em>False Description</em>}</li>
 *   <li>{@link org.xtext.example.oil.oil.impl.ImplAttrBooleanDefImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.oil.oil.impl.ImplAttrBooleanDefImpl#isMultiple <em>Multiple</em>}</li>
 *   <li>{@link org.xtext.example.oil.oil.impl.ImplAttrBooleanDefImpl#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.example.oil.oil.impl.ImplAttrBooleanDefImpl#getDefault <em>Default</em>}</li>
 *   <li>{@link org.xtext.example.oil.oil.impl.ImplAttrBooleanDefImpl#getDescription <em>Description</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class ImplAttrBooleanDefImpl extends ImplAttrDefImpl implements ImplAttrBooleanDef
{
  /**
   * The cached value of the '{@link #getTrueParameterList() <em>True Parameter List</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrueParameterList()
   * @generated
   * @ordered
   */
  protected EList<ImplementationDef> trueParameterList;

  /**
   * The default value of the '{@link #getTrueDescription() <em>True Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrueDescription()
   * @generated
   * @ordered
   */
  protected static final String TRUE_DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTrueDescription() <em>True Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrueDescription()
   * @generated
   * @ordered
   */
  protected String trueDescription = TRUE_DESCRIPTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getFalseParameterList() <em>False Parameter List</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFalseParameterList()
   * @generated
   * @ordered
   */
  protected EList<ImplementationDef> falseParameterList;

  /**
   * The default value of the '{@link #getFalseDescription() <em>False Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFalseDescription()
   * @generated
   * @ordered
   */
  protected static final String FALSE_DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getFalseDescription() <em>False Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFalseDescription()
   * @generated
   * @ordered
   */
  protected String falseDescription = FALSE_DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #isMultiple() <em>Multiple</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMultiple()
   * @generated
   * @ordered
   */
  protected static final boolean MULTIPLE_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isMultiple() <em>Multiple</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMultiple()
   * @generated
   * @ordered
   */
  protected boolean multiple = MULTIPLE_EDEFAULT;

  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final String VALUE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected String value = VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getDefault() <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefault()
   * @generated
   * @ordered
   */
  protected static final DefaultEnum DEFAULT_EDEFAULT = DefaultEnum.NO_DEFAULT;

  /**
   * The cached value of the '{@link #getDefault() <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefault()
   * @generated
   * @ordered
   */
  protected DefaultEnum default_ = DEFAULT_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ImplAttrBooleanDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OilPackage.eINSTANCE.getImplAttrBooleanDef();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ImplementationDef> getTrueParameterList()
  {
    if (trueParameterList == null)
    {
      trueParameterList = new EObjectContainmentEList<ImplementationDef>(ImplementationDef.class, this, OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_PARAMETER_LIST);
    }
    return trueParameterList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTrueDescription()
  {
    return trueDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTrueDescription(String newTrueDescription)
  {
    String oldTrueDescription = trueDescription;
    trueDescription = newTrueDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_DESCRIPTION, oldTrueDescription, trueDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ImplementationDef> getFalseParameterList()
  {
    if (falseParameterList == null)
    {
      falseParameterList = new EObjectContainmentEList<ImplementationDef>(ImplementationDef.class, this, OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_PARAMETER_LIST);
    }
    return falseParameterList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getFalseDescription()
  {
    return falseDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFalseDescription(String newFalseDescription)
  {
    String oldFalseDescription = falseDescription;
    falseDescription = newFalseDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_DESCRIPTION, oldFalseDescription, falseDescription));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OilPackage.IMPL_ATTR_BOOLEAN_DEF__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isMultiple()
  {
    return multiple;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMultiple(boolean newMultiple)
  {
    boolean oldMultiple = multiple;
    multiple = newMultiple;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OilPackage.IMPL_ATTR_BOOLEAN_DEF__MULTIPLE, oldMultiple, multiple));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setValue(String newValue)
  {
    String oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OilPackage.IMPL_ATTR_BOOLEAN_DEF__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DefaultEnum getDefault()
  {
    return default_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDefault(DefaultEnum newDefault)
  {
    DefaultEnum oldDefault = default_;
    default_ = newDefault == null ? DEFAULT_EDEFAULT : newDefault;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OilPackage.IMPL_ATTR_BOOLEAN_DEF__DEFAULT, oldDefault, default_));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OilPackage.IMPL_ATTR_BOOLEAN_DEF__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_PARAMETER_LIST:
        return ((InternalEList<?>)getTrueParameterList()).basicRemove(otherEnd, msgs);
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_PARAMETER_LIST:
        return ((InternalEList<?>)getFalseParameterList()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_PARAMETER_LIST:
        return getTrueParameterList();
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_DESCRIPTION:
        return getTrueDescription();
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_PARAMETER_LIST:
        return getFalseParameterList();
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_DESCRIPTION:
        return getFalseDescription();
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__NAME:
        return getName();
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__MULTIPLE:
        return isMultiple();
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__VALUE:
        return getValue();
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__DEFAULT:
        return getDefault();
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__DESCRIPTION:
        return getDescription();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_PARAMETER_LIST:
        getTrueParameterList().clear();
        getTrueParameterList().addAll((Collection<? extends ImplementationDef>)newValue);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_DESCRIPTION:
        setTrueDescription((String)newValue);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_PARAMETER_LIST:
        getFalseParameterList().clear();
        getFalseParameterList().addAll((Collection<? extends ImplementationDef>)newValue);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_DESCRIPTION:
        setFalseDescription((String)newValue);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__NAME:
        setName((String)newValue);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__MULTIPLE:
        setMultiple((Boolean)newValue);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__VALUE:
        setValue((String)newValue);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__DEFAULT:
        setDefault((DefaultEnum)newValue);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__DESCRIPTION:
        setDescription((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_PARAMETER_LIST:
        getTrueParameterList().clear();
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_DESCRIPTION:
        setTrueDescription(TRUE_DESCRIPTION_EDEFAULT);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_PARAMETER_LIST:
        getFalseParameterList().clear();
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_DESCRIPTION:
        setFalseDescription(FALSE_DESCRIPTION_EDEFAULT);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__NAME:
        setName(NAME_EDEFAULT);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__MULTIPLE:
        setMultiple(MULTIPLE_EDEFAULT);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__DEFAULT:
        setDefault(DEFAULT_EDEFAULT);
        return;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_PARAMETER_LIST:
        return trueParameterList != null && !trueParameterList.isEmpty();
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__TRUE_DESCRIPTION:
        return TRUE_DESCRIPTION_EDEFAULT == null ? trueDescription != null : !TRUE_DESCRIPTION_EDEFAULT.equals(trueDescription);
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_PARAMETER_LIST:
        return falseParameterList != null && !falseParameterList.isEmpty();
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__FALSE_DESCRIPTION:
        return FALSE_DESCRIPTION_EDEFAULT == null ? falseDescription != null : !FALSE_DESCRIPTION_EDEFAULT.equals(falseDescription);
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__MULTIPLE:
        return multiple != MULTIPLE_EDEFAULT;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__VALUE:
        return VALUE_EDEFAULT == null ? value != null : !VALUE_EDEFAULT.equals(value);
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__DEFAULT:
        return default_ != DEFAULT_EDEFAULT;
      case OilPackage.IMPL_ATTR_BOOLEAN_DEF__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (trueDescription: ");
    result.append(trueDescription);
    result.append(", falseDescription: ");
    result.append(falseDescription);
    result.append(", name: ");
    result.append(name);
    result.append(", multiple: ");
    result.append(multiple);
    result.append(", value: ");
    result.append(value);
    result.append(", default: ");
    result.append(default_);
    result.append(", description: ");
    result.append(description);
    result.append(')');
    return result.toString();
  }

} //ImplAttrBooleanDefImpl
