/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.oil.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.oil.ui.internal.OilActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OilExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return OilActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return OilActivator.getInstance().getInjector(OilActivator.ORG_XTEXT_EXAMPLE_OIL_OIL);
	}
	
}
